#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  4 18:15:28 2017

@author: raviteja
"""

#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  4 17:56:22 2017

@author: raviteja
"""

#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  4 13:35:37 2017

@author: raviteja
"""

#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 30 22:57:46 2017

@author: raviteja
"""

from PIL import Image
from numpy import array
from collections import Iterable
import numpy as np
from sklearn import tree
import matplotlib.pyplot as plt
 






img1 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/1.jpg")
img2 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/2.jpg")
img3 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/3.jpg")
img4 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/4.jpg")
img5 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/5.jpg")
img6 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/6.jpg")
img7 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/7.jpg")
img8 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/8.jpg")
img9 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/9.jpg")
img10 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/10.jpg")
img11 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/11.jpg")
img12 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/12.jpg")
img13 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/13.jpg")
img14 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/14.jpg")
img15 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/15.jpg")
img16 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/16.jpg")
img17 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/17.jpg")
img18 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/18.jpg")
img19 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/19.jpg")
img20 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/20.jpg")
img21 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/21.jpg")
img22 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/22.jpg")
img23 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/23.jpg")
img24 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/24.jpg")
img25 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/25.jpg")
img26 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/26.jpg")
img27 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/27.jpg")
img28 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/28.jpg")
img29 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/29.jpg")
img30 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/30.jpg")


img31 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/1.jpg")
img32 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/2.jpg")
img33 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/3.jpg")
img34 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/4.jpg")
img35 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/5.jpg")
img36 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/6.jpg")
img37 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/7.jpg")
img38 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/8.jpg")
img39 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/9.jpg")
img40 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/10.jpg")
img41 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/11.jpg")
img42 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/12.jpg")
img43 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/13.jpg")
img44 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/14.jpg")
img45 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/15.jpg")
img46 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/16.jpg")
img47 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/17.jpg")
img48 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/18.jpg")
img49 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/19.jpg")
img50 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/20.jpg")
img51 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/21.jpg")
img52 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/22.jpg")
img53 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/23.jpg")
img54 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/24.jpg")
img55 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/25.jpg")
img56 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/26.jpg")
img57 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/27.jpg")
img58 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/28.jpg")
img59 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/29.jpg")
img60 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/30.jpg")


img61 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/31.jpg")
img62 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/32.jpg")
img63 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/33.jpg")
img64 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/34.jpg")
img65 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/35.jpg")
img66 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/36.jpg")
img67 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/37.jpg")
img68 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/38.jpg")
img69 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/39.jpg")
img70 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/40.jpg")
img71 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/41.jpg")
img72 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/42.jpg")
img73 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/43.jpg")
img74 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/44.jpg")
img75 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/45.jpg")
img76 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/46.jpg")
img77 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/47.jpg")
img78 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/48.jpg")
img79 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/49.jpg")
img80 = Image.open("/home/raviteja/Desktop/Project images/Water_Selfie/50.jpg")

img81 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/31.jpg")
img82 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/32.jpg")
img83 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/33.jpg")
img84 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/34.jpg")
img85 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/35.jpg")
img86 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/36.jpg")
img87 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/37.jpg")
img88 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/38.jpg")
img89 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/39.jpg")
img90 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/40.jpg")
img91 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/41.jpg")
img92 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/42.jpg")
img93 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/43.jpg")
img94 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/44.jpg")
img95 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/45.jpg")
img96 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/46.jpg")
img97 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/47.jpg")
img98 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/48.jpg")
img99 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/49.jpg")
img100 = Image.open("/home/raviteja/Desktop/Project images/Animal_Selfie/50.jpg")






#print           arr1,arr2,arr3,arr4,arr5,arr6,arr7,arr8,arr9,arr10,arr11,arr12,arr13,arr14,arr15,arr16,arr17,arr18,arr19,arr20,arr21,arr22,arr23,arr24,arr25,arr26,arr27,arr28,arr29,arr30,arr31,arr32,arr33,arr34,arr35,arr36,arr37,arr38,arr39,arr40,arr41,arr42,arr43,arr44
arr1 = np.array(img1).flatten()
arr2 = np.array(img2).flatten()
arr3 = np.array(img3).flatten()
arr4 = np.array(img4).flatten()
arr5 = np.array(img5).flatten()
arr6 = np.array(img6).flatten()
arr7 = np.array(img7).flatten()
arr8 = np.array(img8).flatten()
arr9 = np.array(img9).flatten()
arr10 = np.array(img10).flatten()
arr11 = np.array(img11).flatten()
arr12 = np.array(img12).flatten()
arr13 = np.array(img13).flatten()
arr14 = np.array(img14).flatten()
arr15 = np.array(img15).flatten()
arr16 = np.array(img16).flatten()
arr17 = np.array(img17).flatten()
arr18 = np.array(img18).flatten()
arr19 = np.array(img19).flatten()
arr20 = np.array(img20).flatten()
arr21 = np.array(img21).flatten()
arr22 = np.array(img22).flatten()
arr23 = np.array(img23).flatten()
arr24 = np.array(img24).flatten()
arr25 = np.array(img25).flatten()
arr26 = np.array(img26).flatten()
arr27 = np.array(img27).flatten()
arr28 = np.array(img28).flatten()
arr29 = np.array(img29).flatten()
arr30 = np.array(img30).flatten()
arr31 = np.array(img31).flatten()
arr32 = np.array(img32).flatten()
arr33 = np.array(img33).flatten()
arr34 = np.array(img34).flatten()
arr35 = np.array(img35).flatten()
arr36 = np.array(img36).flatten()
arr37 = np.array(img37).flatten()
arr38 = np.array(img38).flatten()
arr39 = np.array(img39).flatten()
arr40 = np.array(img40).flatten()
arr41 = np.array(img41).flatten()
arr42 = np.array(img42).flatten()
arr43 = np.array(img43).flatten()
arr44 = np.array(img44).flatten()
arr45 = np.array(img45).flatten()
arr46 = np.array(img46).flatten()
arr47 = np.array(img47).flatten()
arr48 = np.array(img48).flatten()
arr49 = np.array(img49).flatten()
arr50 = np.array(img50).flatten()
arr51 = np.array(img51).flatten()
arr52 = np.array(img52).flatten()
arr53 = np.array(img53).flatten()
arr54 = np.array(img54).flatten()
arr55 = np.array(img55).flatten()
arr56 = np.array(img56).flatten()
arr57 = np.array(img57).flatten()
arr58 = np.array(img58).flatten()
arr59 = np.array(img59).flatten()
arr60 = np.array(img60).flatten()
arr61 = np.array(img61).flatten()
arr62 = np.array(img62).flatten()
arr63 = np.array(img63).flatten()
arr64 = np.array(img64).flatten()
arr65 = np.array(img65).flatten()
arr66 = np.array(img66).flatten()
arr67 = np.array(img67).flatten()
arr68 = np.array(img68).flatten()
arr69 = np.array(img69).flatten()
arr70 = np.array(img70).flatten()
arr71 = np.array(img71).flatten()
arr72 = np.array(img72).flatten()
arr73 = np.array(img73).flatten()
arr74 = np.array(img74).flatten()
arr75 = np.array(img75).flatten()
arr76 = np.array(img76).flatten()
arr77 = np.array(img77).flatten()
arr78 = np.array(img78).flatten()
arr79 = np.array(img79).flatten()
arr80 = np.array(img80).flatten()
arr81 = np.array(img81).flatten()
arr82 = np.array(img82).flatten()
arr83 = np.array(img83).flatten()
arr84 = np.array(img84).flatten()
arr85 = np.array(img85).flatten()
arr86 = np.array(img86).flatten()
arr87 = np.array(img87).flatten()
arr88 = np.array(img88).flatten()
arr89 = np.array(img89).flatten()
arr90 = np.array(img90).flatten()
arr91 = np.array(img91).flatten()
arr92 = np.array(img92).flatten()
arr93 = np.array(img93).flatten()
arr94 = np.array(img94).flatten()
arr95 = np.array(img95).flatten()
arr96 = np.array(img96).flatten()
arr97 = np.array(img97).flatten()
arr98 = np.array(img98).flatten()
arr99 = np.array(img99).flatten()
arr100 = np.array(img100).flatten()



X = []
Y = []

label = 0
labell = 1


X.append(arr1)
X.append(arr2)
X.append(arr3)
X.append(arr4)
X.append(arr5)
X.append(arr6)
X.append(arr7)
X.append(arr8)
X.append(arr9)
X.append(arr10)
X.append(arr11)
X.append(arr12)
X.append(arr13)
X.append(arr14)
X.append(arr15)
X.append(arr16)
X.append(arr17)
X.append(arr18)
X.append(arr19)
X.append(arr20)
X.append(arr21)
X.append(arr22)
X.append(arr23)
X.append(arr24)
X.append(arr25)
X.append(arr26)
X.append(arr27)
X.append(arr28)
X.append(arr29)
X.append(arr30)
X.append(arr31)
X.append(arr32)
X.append(arr33)
X.append(arr34)
X.append(arr35)
X.append(arr36)
X.append(arr37)
X.append(arr38)
X.append(arr39)
X.append(arr40)
X.append(arr41)
X.append(arr42)
X.append(arr43)
X.append(arr44)
X.append(arr45)
X.append(arr46)
X.append(arr47)
X.append(arr48)
X.append(arr49)
X.append(arr50)
X.append(arr51)
X.append(arr52)
X.append(arr53)
X.append(arr54)
X.append(arr55)
X.append(arr56)
X.append(arr57)
X.append(arr58)
X.append(arr59)
X.append(arr60)
X.append(arr61)
X.append(arr62)
X.append(arr63)
X.append(arr64)
X.append(arr65)
X.append(arr66)
X.append(arr67)
X.append(arr68)
X.append(arr69)
X.append(arr70)
X.append(arr71)
X.append(arr72)
X.append(arr73)
X.append(arr74)
X.append(arr75)
X.append(arr76)
X.append(arr77)
X.append(arr78)
X.append(arr79)
X.append(arr80)
X.append(arr81)
X.append(arr82)
X.append(arr83)
X.append(arr84)
X.append(arr85)
X.append(arr86)
X.append(arr87)
X.append(arr88)
X.append(arr89)
X.append(arr90)
X.append(arr91)
X.append(arr92)
X.append(arr93)
X.append(arr94)
X.append(arr95)
X.append(arr96)
X.append(arr97)
X.append(arr98)
X.append(arr99)
X.append(arr100)

Y.append(label)
Y.append(label)    
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)

Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)

Y.append(label)
Y.append(label)    
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)
Y.append(label)

Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)
Y.append(labell)



X = X[0].shape,X[1].shape,X[2].shape,X[3].shape,X[4].shape,X[5].shape,X[6].shape,X[7].shape,X[8].shape,X[9].shape,X[10].shape,X[11].shape,X[12].shape,X[13].shape,X[14].shape,X[15].shape,X[16].shape,X[17].shape,X[18].shape,X[19].shape,X[20].shape,X[21].shape,X[22].shape,X[23].shape,X[24].shape,X[25].shape,X[26].shape,X[27].shape,X[28].shape,X[29].shape,X[30].shape,X[31].shape,X[32].shape,X[33].shape,X[34].shape,X[35].shape,X[36].shape,X[37].shape,X[38].shape,X[39].shape,X[40].shape,X[41].shape,X[42].shape,X[43].shape,X[44].shape,X[45].shape,X[46].shape,X[47].shape,X[48].shape,X[49].shape,X[50].shape,X[51].shape,X[52].shape,X[53].shape,X[54].shape,X[55].shape,X[56].shape,X[57].shape,X[58].shape,X[59].shape,X[60].shape,X[61].shape,X[62].shape,X[63].shape,X[64].shape,X[65].shape,X[66].shape,X[67].shape,X[68].shape,X[69].shape,X[70].shape,X[71].shape,X[72].shape,X[73].shape,X[74].shape,X[75].shape,X[76].shape,X[77].shape,X[78].shape,X[79].shape,X[80].shape,X[81].shape,X[82].shape,X[84].shape,X[85].shape,X[87].shape,X[86].shape,X[88].shape,X[89].shape,X[90].shape,X[91].shape,X[92].shape,X[93].shape,X[94].shape,X[95].shape,X[96].shape,X[97].shape,X[98].shape,X[99].shape,X[83].shape

X = np.vstack(X)


X = np.array(X)
Y = np.array(Y)

print X.shape # this should give you n x 196,608
print Y.shape

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)



from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier()
neigh.fit(X, Y)

Y_pred = neigh.predict(X_test)

from sklearn.metrics import accuracy_score

print accuracy_score(Y_test,Y_pred)







